In [1]:
import pandas as pd
import numpy as np

In [6]:
df=pd.read_csv('https://raw.githubusercontent.com/nethajinirmal13/Training-datasets/main/diabetes.csv')
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [5]:
df.isna()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
763,False,False,False,False,False,False,False,False,False
764,False,False,False,False,False,False,False,False,False
765,False,False,False,False,False,False,False,False,False
766,False,False,False,False,False,False,False,False,False
767,False,False,False,False,False,False,False,False,False

In [7]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [18]:
X=df[["Glucose","BloodPressure","Insulin"]].values
y=df[['Outcome']].values

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [20]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [21]:
print(model.intercept_)
print(model.coef_)

[-0.51263446]
[[ 0.00715713  0.00021715 -0.00013111]]

In [22]:
y_pred = model.predict(X_test)
y_pred

array([[ 0.92813718],
       [ 0.2561361 ],
       [ 0.04477033],
       [ 0.66813917],
       [ 0.29592127],
       [ 0.07748305],
       [ 0.56976669],
       [ 0.74524158],
       [ 0.37286016],
       [ 0.21527343],
       [ 0.60257305],
       [ 0.81511195],
       [ 0.31934697],
       [ 0.07046404],
       [-0.03178663],
       [ 0.27510132],
       [ 0.76708178],
       [ 0.0206932 ],
       [ 0.45078103],
       [ 0.19676503],
       [ 0.53579799],
       [ 0.34927835],
       [ 0.11003573],
       [-0.05824369],
       [ 0.17758327],
       [ 0.38787821],
       [ 0.24820997],
       [ 0.58315967],
       [ 0.30329554],
       [ 0.28941558],
       [ 0.45910399],
       [ 0.22106342],
       [ 0.22230066],
       [ 0.35111147],
       [ 0.34423422],
       [ 0.70366045],
       [ 0.461931  ],
       [ 0.33498389],
       [ 0.34035834],
       [ 0.78036832],
       [ 0.34089907],
       [ 0.14844446],
       [ 0.20187008],
       [ 0.88389154],
       [ 0.84132752],
       [ 0.23367857],
       [ 0.26645631],
       [ 0.40945483],
       [ 0.26841001],
       [ 0.39937825],
       [ 0.45402953],
       [ 0.26336709],
       [ 0.54776143],
       [ 0.48743525],
       [ 0.12589711],
       [-0.50221148],
       [ 0.11005307],
       [ 0.33171559],
       [ 0.46162095],
       [ 0.31043533],
       [ 0.67533711],
       [ 0.51711708],
       [ 0.39677251],
       [ 0.47504928],
       [ 0.80603171],
       [ 0.91338864],
       [ 0.68740056],
       [ 0.37747258],
       [ 0.25731274],
       [ 0.01961615],
       [ 0.27423274],
       [ 0.33906384],
       [ 0.11764449],
       [ 0.81753175],
       [ 0.726869  ],
       [ 0.48613238],
       [-0.00935667],
       [ 0.58032795],
       [ 0.10008173],
       [ 0.1968072 ],
       [ 0.21958146],
       [ 0.45005743],
       [ 0.27432975],
       [ 0.18475333],
       [ 0.18032149],
       [ 0.16319301],
       [ 0.49393227],
       [ 0.22018205],
       [ 0.77587298],
       [ 0.1602582 ],
       [ 0.39091825],
       [ 0.42887535],
       [ 0.29583403],
       [ 0.23117043],
       [ 0.67015621],
       [ 0.28863243],
       [ 0.18617909],
       [ 0.55739319],
       [ 0.27030159],
       [ 0.3260698 ],
       [ 0.28328359],
       [ 0.19488853],
       [ 0.29462707],
       [ 0.17664219],
       [ 0.41737531],
       [ 0.27553561],
       [ 0.3921051 ],
       [ 0.48309234],
       [ 0.20490189],
       [ 0.81101738],
       [ 0.12768954],
       [ 0.28382569],
       [ 0.52516653],
       [ 0.4171539 ],
       [ 0.68164304],
       [ 0.65833775],
       [ 0.23734997],
       [ 0.83038252],
       [ 0.30048133],
       [ 0.34392616],
       [ 0.30590129],
       [ 0.2480015 ],
       [ 0.30641158],
       [ 0.37031545],
       [ 0.51890601],
       [ 0.14453584],
       [ 0.39510768],
       [ 0.33366122],
       [ 0.46530376],
       [ 0.75897185],
       [ 0.47774838],
       [ 0.23886404],
       [ 0.08012169],
       [ 0.65724507],
       [ 0.16367528],
       [ 0.23389571],
       [ 0.26403557],
       [ 0.23888139],
       [ 0.49652067],
       [ 0.35794683],
       [ 0.11581246],
       [ 0.588678  ],
       [ 0.25145848],
       [-0.05195514],
       [ 0.3176098 ],
       [ 0.20851571],
       [ 0.12850894],
       [ 0.07426743],
       [ 0.19637291],
       [ 0.23119374],
       [ 0.10189154],
       [ 0.52235231],
       [ 0.31989471],
       [ 0.25806178],
       [ 0.56135236],
       [ 0.19463574],
       [ 0.5986803 ],
       [ 0.2619529 ],
       [ 0.34622097],
       [ 0.4535779 ],
       [ 0.63712266],
       [ 0.89278583],
       [-0.00401968],
       [ 0.35966634],
       [ 0.78369174],
       [ 0.33906384],
       [ 0.04433604],
       [ 0.29483554],
       [ 0.39460105],
       [ 0.25840714],
       [ 0.12628373],
       [ 0.02576887],
       [ 0.26924707],
       [ 0.23346142],
       [ 0.52104944],
       [ 0.14232678],
       [ 0.18292723],
       [ 0.05076377],
       [ 0.27804178],
       [ 0.15256155],
       [ 0.23519859],
       [ 0.64294644],
       [ 0.08686843],
       [ 0.78998029],
       [ 0.47593521],
       [-0.18425778],
       [ 0.42494938],
       [ 0.39048396],
       [ 0.51288669],
       [ 0.25665933],
       [ 0.42041535],
       [ 0.1341302 ],
       [ 0.137813  ],
       [ 0.33217685],
       [ 0.15603588],
       [ 0.46455884],
       [ 0.52547657],
       [ 0.56579123],
       [ 0.22868422],
       [ 0.21416149],
       [ 0.27140788],
       [ 0.46813641],
       [ 0.21240546],
       [ 0.48027812],
       [ 0.31001838],
       [ 0.04328245],
       [ 0.18292723],
       [ 0.20919577],
       [ 0.60020271],
       [ 0.37324312],
       [ 0.18103018],
       [ 0.12488705],
       [ 0.30459842],
       [ 0.58112069],
       [ 0.29140553],
       [ 0.07773704],
       [ 0.32684582],
       [ 0.43928099],
       [ 0.65052052],
       [ 0.19138723],
       [ 0.18119007],
       [ 0.22413284],
       [ 0.40816474],
       [ 0.41528184],
       [ 0.55792081],
       [ 0.50782091],
       [ 0.22732258],
       [ 0.26904911],
       [ 0.17271713],
       [ 0.26252423],
       [ 0.37747258]])

In [23]:
from sklearn import metrics
print("MAE",metrics.mean_absolute_error(y_test,y_pred))
print("MSE",metrics.mean_squared_error(y_test,y_pred))
print("RMSE",np.sqrt(metrics.mean_squared_error(y_test,y_pred)))

MAE 0.35909176522234004
MSE 0.17362326334708109
RMSE 0.416681249094654

In [24]:
score=model.score(X_test,y_test)
print(score)
print(score*100,'%')

0.20255543506080276
20.255543506080276 %

In [25]:
model.predict([[110,102,90]])

array([[0.28499866]])